from pathlib import Path
import os
import sys
from agents import function_tool

@function_tool
def createFolder(folderName:str):

    """
    Create a structured email template directory inside the "email_Templates" root.

    IMPORTANT (for agent reasoning and decision making):

    - The agent MUST derive `folderName` from the PRIMARY PURPOSE of the email.
    - The name should represent the email category, not specific content or users.
    - Use lowercase, snake_case, and semantic naming.

    Naming rules:
    - Derive name from intent (welcome, verification, reset, invoice, etc.)
    - Use snake_case
    - No spaces, no special characters
    - No file extensions
    - No user identifiers or timestamps

    Examples of valid folder names:
    - "welcome_email"
    - "email_verification"
    - "password_reset"
    - "order_confirmation"
    - "invoice_notification"
    - "otp_login"
    - "marketing_campaign"

    Folder structure created by this tool:

    email_Templates/
        └── <folderName>/
            ├── src/
            │   └── (MJML source templates: *.mjml)
            └── build/
                └── (Compiled HTML output: *.html)

    Subfolder purposes:
    - src/   → Store MJML source templates generated by the MJML creator agent tool.
    - build/ → Store compiled HTML files produced from MJML.

    Agent behavior guidelines:
    - Always call this tool BEFORE generating MJML files.
    - Place all MJML templates inside the src/ directory.
    - Place all compiled HTML output inside the build/ directory.
    - Reuse the same folder for future versions of the same email purpose.

    Args:
        folderName (str): A semantic, snake_case name derived from the email's purpose.

    Returns:
        str: Confirmation message including the full path of the created directory.
    """
    print("==============================Generating Folder ============================================",)
    
    if not folderName or not  isinstance(folderName , str):
        raise ValueError("Invalid folder name provided , it should be a non-empty string") 
    
    rootIs:str="email_Templates"
    folderIs=Path(rootIs)/ folderName
    folderIs.mkdir(parents=True , exist_ok=True)
    
    srcFolderIs=folderIs / "src"
    buildFolderIs=folderIs / "build"
    
    srcFolderIs.mkdir(parents=True , exist_ok=True)
    buildFolderIs.mkdir(parents=True , exist_ok=True)
    return f"Folder '{folderName}' created successfully in root directory {rootIs}.  and actual path Is Now {folderIs}"
    



